<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>CustomAudioHub</AssemblyName>
		<RootNamespace>CustomAudioHub</RootNamespace>
		<Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>
		<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
		<OutputType>Library</OutputType>
		<FileAlignment>512</FileAlignment>
		<LangVersion>12</LangVersion>
		<IsPackable>false</IsPackable>
		<TargetFramework>net48</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<IsPackable>false</IsPackable>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ImplicitUsings>enable</ImplicitUsings>
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<Version>0.0.2</Version>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/KadavasKingdom/CustomAudioHub</RepositoryUrl>
		<PackageProjectUrl>https://github.com/KadavasKingdom/CustomAudioHub</PackageProjectUrl>
		<Authors>$(AssemblyName);KadavasKingdom;Kadava</Authors>
	</PropertyGroup>
	<!-- Nuget References -->
	<ItemGroup>
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all" ExcludeAssets="runtime" ReferenceOutputAssembly="false" Private="true" />
		<PackageReference Include="Northwood.LabAPI" Version="1.1.1" Publicize="true" PrivateAssets="all" ExcludeAssets="runtime" ReferenceOutputAssembly="false" Private="true" />
	</ItemGroup>
	<!-- Usings globals -->
	<ItemGroup>
		<Using Include="LabApi.Features.Console.Logger" Alias="CL" />
	</ItemGroup>

	<!-- Remove unnessessary files in VS -->
	<ItemGroup>
		<None Remove=".*;*.md;LICENSE" />
	</ItemGroup>

	<Import Project="ReferencePaths.props.user" Condition="Exists('ReferencePaths.props.user')" />
	<PropertyGroup>
		<AssemblySearchPaths>$(AssemblySearchPaths);$(ReferencePath);..\3rdparty;$(SL_REFERENCES)</AssemblySearchPaths>
	</PropertyGroup>
</Project>